export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST" 
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS" 
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED" 

export const GET_MOVIES_SEARCHMOVIES = "GET_MOVIES_SEARCHMOVIES" 
export const GET_MOVIES_SEARCHMOVIESBYBTN = "GET_MOVIES_SEARCHMOVIESBYBTN" 
export const GET_MOVIES_GETMOVIEDETAILS = "GET_MOVIES_GETMOVIEDETAILS" 

export const GET_TOKEN = "GET_TOKEN" 